joints:
  shoulder_lateral:
    type: PosVelControlledJoint
    default_rpm: 5.0
  sholder_vertical:
    type: PosVelControlledJoint
    default_rpm: 5.0
  elbow:
    type: PosVelControlledJoint
    default_rpm: 5.0
  lower_arm_yaw:
    type: PosVelControlledJoint
    default_rpm: 5.0
  lower_arm_vertical:
    type: PosVelControlledJoint
    default_rpm: 5.0
  gripper_yaw:
    type: PosVelControlledJoint
    default_rpm: 5.0
  left_finger_joint:
    type: PositionControlledJoint
    default_rpm: 10.0
