joints:
  shoulder_lateral:
    type: PositionControlledJoint
    default_rpm: 5.0
  sholder_vertical:
    type: PositionControlledJoint
    default_rpm: 5.0
  elbow:
    type: PositionControlledJoint
    default_rpm: 5.0
  lower_arm_yaw:
    type: PositionControlledJoint
    default_rpm: 5.0
  lower_arm_vertical:
    type: PositionControlledJoint
    default_rpm: 5.0
  gripper_yaw:
    type: PositionControlledJoint
    default_rpm: 5.0
  left_finger_joint:
    type: PositionControlledJoint
    default_rpm: 10.0
  slider_joint:
    type: PositionControlledJoint
    default_speed: 0.012 # 2400 micro steps/s : 2400*(1.8/8)*(0.008/360) 

  

